# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.new({:email => "admin@thermmonitor.com.bo", :password => "usuarioadmin", :password_confirmation => "usuarioadmin" }).save(:validate => false)
User.new({:email => "user1@thermmonitor.com.bo", :password => "usuariouno", :password_confirmation => "usuariouno" }).save(:validate => false)
User.new({:email => "user2@thermmonitor.com.bo", :password => "usuariodos", :password_confirmation => "usuariodos" }).save(:validate => false)
Location.new({:name => "Casa", :address => "Cochabamba, Av. Circunvalacion", :user_id => 2}).save(:validate => true)
Location.new({:name => "Oficina", :address => "Cochabamba, Av. Pando", :user_id => 2}).save(:validate => true)
Location.new({:name => "Ferreteria", :address => "Cochabamba, Av. Libertadores", :user_id => 3}).save(:validate => true)
Location.new({:name => "Carniceria", :address => "Cochabamba, Av. America", :user_id => 3}).save(:validate => true)
Thermostat.new({:serial => "123", :temperature => 30, :user_id => 2, :energy => 10, :default_temperature => 30, :location_id => 1}).save(:validate => false)
Thermostat.new({:serial => "1234", :temperature => 50, :user_id => 2, :energy => 20, :default_temperature => 50, :location_id => 1}).save(:validate => false)
Thermostat.new({:serial => "12345", :temperature => 40, :user_id => 2, :energy => 30, :default_temperature => 40, :location_id => 2}).save(:validate => false)
Thermostat.new({:serial => "123556", :temperature => 10, :user_id => 2, :energy => 40, :default_temperature => 10, :location_id => 2}).save(:validate => false)
Thermostat.new({:serial => "0012", :temperature => 30, :user_id => 3, :energy => 10, :default_temperature => 30, :location_id => 3}).save(:validate => false)
Thermostat.new({:serial => "00123", :temperature => 50, :user_id => 3, :energy => 20, :default_temperature => 50, :location_id => 3}).save(:validate => false)
Thermostat.new({:serial => "001234", :temperature => 40, :user_id => 3, :energy => 30, :default_temperature => 40, :location_id => 4}).save(:validate => false)
Thermostat.new({:serial => "0012345", :temperature => 10, :user_id => 3, :energy => 40, :default_temperature => 10, :location_id => 4}).save(:validate => false)
Issue.new({:description => "Termostato quemado", :status => "Open", :thermostat_id => 1}).save(:validate => false)
Issue.new({:description => "Termostato dañado", :status => "Open", :thermostat_id => 2}).save(:validate => false)
Issue.new({:description => "El Termostato no enciende", :status => "Open", :thermostat_id => 3}).save(:validate => false)
Issue.new({:description => "El Termostato dejo de funcionar", :status => "Open", :thermostat_id => 4}).save(:validate => false)
Issue.new({:description => "El Termostato no me envia la temperatura", :status => "Open", :thermostat_id => 5}).save(:validate => false)
Issue.new({:description => "El Termostato no me cambia la temperatura", :status => "Open", :thermostat_id => 6}).save(:validate => false)
Issue.new({:description => "El Termostato no funciona", :status => "Open", :thermostat_id => 7}).save(:validate => false)
Issue.new({:description => "El Termostato exploto", :status => "Open", :thermostat_id => 8}).save(:validate => false)
